### PR TITLE
Changes to work with what I pushed to the 3.8 kernel

### PR DESCRIPTION
**Pull request by jadonk**

### CODE REVIEW

**Comment by jadonk** [comment]
I've done some additional updates. It is mostly cleaning up the process of building, installing and removing extraneous files.

**Comment by jadonk** [comment]
@RobertCNelson I think with this added, this should be reasonable to package up as a .deb. Lots more functionality is still needed, but it is fun for GPIO usage as a bit of a Hello World for PRU.

**Comment by RobertCNelson** [comment]
@jadonk sure i'll start on the packing tomorrow, looks like it has a fun kernel module, i should push that out as a 3rd party module asap to get it built against the kernel

**Comment by deepakkarki** [comment]
@jadonk , don't know how I missed the long due pull request. 

But last I remember you had modified the kernel driver (making it modular - like the beagle logic driver), couldn't find that in the commit log.

**Comment by jadonk** [comment]
Yeah, I don't see it either. Need to rediff against https://github.com/jadonk/linux-1/commit/4e7bc5501d6a7366a4e311fe48698a6df5382409.

**Comment by deepakkarki** [comment]
Yeah, I hadn't pulled it in that time, cause something wasn't right. (There was a bug or something with my driver I had to fix first). Now I can't find what was wrong :(

**Pull request merged**
